---
always_allow_html: yes
output:
  html_document: default
params: 
  lang: "FR"
  numpage: 17
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE)
knitr::read_chunk("../../R/tool.R")
knitr::read_chunk("../../R/data.R")
knitr::read_chunk("../../R/ccze_init_table.R")
# knitr::read_chunk("../../R/ccze_footer.R")
```
```{r}
<<init>>
<<tool>>
<<data>>
```
```{r include=T}
includeCSS("../../css/ccze.css")
```
```{r}
data.collection <- getDataCollection("../../data/input/ze_bm_piemf")
```

## `r ifelse(params$lang=="FR","Prix &agrave; la consommation : indices harmonis&eacute;s","Consumer prices: harmonised indices")`

***
<p class="unitlegend">*`r ifelse(params$lang=="FR","Variation en pourcentage","Percentage change")`*</p>

```{r}

genDataTable <- function(data,met,sketch) {
  
  countries.highlight <- c("France","Zone euro","Union européenne","États-Unis","Japon")
  countries.highlight.code <- getCountryByName(countries.highlight) 
  decimal.sep <- ifelse(params$lang=="FR",",",".")
  
  res <- DT::datatable(cbind(country=met[-1],sapply(data[-1,],as.numeric)),
                       rownames=F, container=sketch,
                       options = list(paging=F,searching=F,info=F,
                                      language=list(decimal=decimal.sep),
                                      columnDefs = list(list(className='dt-right',targets=1:ncol(data),
                                                             defaultContent=ifelse(params$lang=="FR",
                                                                                   "<i>nd</i>","<i>na</i>"))),
                                      rowCallback=DT::JS(
                                        highlightTableRowByCountry(country=countries.highlight.code,begin=0,end=ncol(data),width="1px")
                                      )
                       ),
                       class="compact hover stripe",escape=F) %>%
    formatCurrency(columns=c(1:ncol(data)+1),currency="",dec.mark=decimal.sep,digits=1) %>%
    formatStyle(1,target="row",
                fontWeight=styleEqual(countrynameFR2EN(
                  countries.highlight),rep("bold",5)),
                color=styleEqual(countrynameFR2EN(countries.highlight),
                                 eval(parse(text=sub(",)",")",paste0(
                                   "c(",
                                   paste0("style.color.",countries.highlight.code,",",collapse=""),
                                   ")"))))
                )) %>%
    formatStyle(c(5,11), `box-shadow`='-2px 0 0 black')
  
  return(res)
  
}

#get data & metadata
data.y.0 <- getData(data.collection,"ZEB010AD2.TXT") #annual average
meta <- data.y.0[[1]] #metadata
data.y.0 <- data.y.0[[2]]
data.m.yoy.0 <- tail(getData(data.collection,"ZEB010AD1.TXT")[[2]][,1:33],6) #monthly change
data.m.mc.0 <- tail(getData(data.collection,"ZEB010AD1.TXT")[[2]][,c(1,34:65)],6) #year-on-year change

#select series
series <- c(1, #variable
            2, #France
            3, #Germany
            4, #Austria
            5, #Belgium
            6, #Cyprus
            7, #Spain
            8, #Estonia
            9, #Finland
            10, #Greece
            11, #Ireland
            12, #Italy
            13, #Latvia
            14, #Lithuania
            15, #Luxembourg,
            16, #Malta
            17, #Netherlands
            18, #Portugal
            19, #Slovakia
            20, #Slovenia
            21, #Euro area
            22, #Bulgaria
            23, #Croatia
            24, #Denmark
            25, #Hungary
            26, #Poland
            27, #Romania
            28, #United Kingdom
            29, #Sweden
            30, #Czech Republic
            31, #European union
            32, #United States
            33)  #Japan

if (all(is.na(tail(data.y.0[,tail(series,length(series)-1)],1)))) { #if last obs is NA then shift one previous
  end <- nrow(data.y.0)-1
  begin <- end-3
  data.y <- t(data.y.0[begin:end,series])
  rm(begin,end)
} else
  data.y <- t(tail(data.y.0[,series],3))

data.m.mc <- t(data.m.mc.0[,series])
data.m.yoy <- t(data.m.yoy.0[,series])

#set metadata:
met <- as.character(meta[2,series])
met <- trimws(unlist(lapply(strsplit(met,":"),"[[",1)))
met <- countrynameFR2EN(met)

#generate datatable:

#header:

col.m.mc <- as.yearmon(as.character(data.m.mc[1,]),"%Y-%m")
# col.m.mc.y <- as.character(format(col.m.mc,"%Y"))
# col.m.mc.m <- as.character(format(col.m.mc,"%b"))

col.m.yoy <- as.yearmon(as.character(data.m.yoy[1,]),"%Y-%m")
# col.m.yoy.y <- as.character(format(col.m.yoy,"%Y"))
# col.m.yoy.m <- as.character(format(col.m.yoy,"%b"))

# t.mc <- base::table(col.m.mc.y)
# t.yoy <- base::table(col.m.yoy.y)

style.sep <- "box-shadow:-2px 0 0 black;"

getTH <- function(variable,liblevel) {
  
  style.fwn <- "font-weight:normal; "
  style.fwb <- "font-weight:bold; text-align:left; border:none;"
  
  res <- htmltools::withTags(
    if (liblevel=="Y") {
      lapply(
        seq_along(variable),
        function(x){th(
          names(variable)[[x]],colspan=variable[x],
          style=paste0(style.fwb,ifelse(x==1,style.sep,""))
        )}) 
    } else { # "M"
      list(
        lapply(utils::head(variable,1),th,style=paste0(style.fwn,style.sep)),
        lapply(tail(variable,length(variable)-1), th, style=style.fwn)
      )
    }
  )
  
  return(res)
  
}

sketch = htmltools::withTags(table(
  thead(
    tr(
      th(colspan=1,rowspan=3),
      th(colspan=3,rowspan=1,ifelse(params$lang=="FR","Moyenne annuelle","Annual average")),
      th(colspan=6,rowspan=1,ifelse(params$lang=="FR","Variation mensuelle","Monthly variation"),
         style=style.sep),
      th(colspan=6,rowspan=1,ifelse(params$lang=="FR","Glissement annuel","Year-on-year"),
         style=style.sep)
    ),
    tr(
      lapply(as.character(data.y[1,]), th, rowspan=2),
      getTH(base::table(as.character(format(col.m.mc,"%Y"))),"Y"),
      getTH(base::table(as.character(format(col.m.yoy,"%Y"))),"Y")
    ),
    tr(
      getTH(as.character(format(col.m.mc,"%b")),"M"),
      getTH(as.character(format(col.m.yoy,"%b")),"M")
    )
  )
))

rm(list=ls(pattern="style\\.(sep|fwn|fwb)|t\\.|col\\.")) #clean-up

#end header

#data
data <- as.data.frame(cbind(data.y,data.m.mc,data.m.yoy), stringsAsFactors=F)
t1 <- genDataTable(data,met,sketch)

#ouput the table
t1

```

<p>&nbsp;</p>

```{r}

htmltools::withTags(footer(style="font-size: 90%",
                           hr(),
                           p(style="text-align: left; font-style: italic; line-height: 50%;",
                             ifelse(params$lang=="FR",
                                    "Indices harmonisés sauf pour les États-Unis et le Japon",
                                    "Harmonised indices except for the United States and Japan")),
                           p(style="text-align: left;",
                             ifelse(params$lang=="FR",
                                    "Sources : nationales, Eurostat",
                                    "Sources: national data, Eurostat"),
                           span(style="float:right;",
                                paste0(ifelse(params$lang=="FR",
                                              "Réalisé le ",
                                              "Produced on "),
                                       format(Sys.Date(),"%e %B %Y")))),
                    p(),
                    p(class="title", style="text-align: left; color: MidnightBlue; font-size: 100%",
                      "Banque de France",
                      span(style="float:right; font-style: italic;",
                           HTML(ifelse(params$lang=="FR",
                                       "Zone euro &bull; Principaux indicateurs économiques et financiers",
                                       "The Euro Area &bull; Main economic and financial indicators")))),
                    p(),
                    p(style="text-align: center; font-weight: bold; color: MidnightBlue;",params$numpage)
))

```


