---
always_allow_html: yes
output:
  html_document:
    css: ../../css/ccze.css
params:
  data.directory: "../../data/input/ze!nonquot"
  data.collection: !r tolower(c("ZEI010AD1.TXT","ZEI010AD2.TXT"))
  data.params: NULL
  data.template: !r c("bdf.bsme2.req","bdf.bsme2.req")
  lang: "FR"
  numpage: 19
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE)
knitr::read_chunk("../../R/tool.R")
knitr::read_chunk("../../R/data.R")
knitr::read_chunk("../../R/ccze_init_table.R")
```
```{r}
<<init>>
<<tool>>
<<data>>
```
```{r}
htmltools::h3(class="pub",ifelse(params$lang=="FR","Indicateurs de performances au sein de la Zone euro","Performance indicators within the Euro area"))
htmltools::hr(class="pub")
htmltools::p(class="unitlegend",ifelse(params$lang=="FR","variation en pourcentage","percentage change"))
```

```{r}
htmltools::p(class="titlechart title",
             ifelse(params$lang=="FR","Coût total horaire de la main-d'ouvre","Hourly labour cost"),
             tags$sup("(a)(b)")
             )
```

```{r}

#get data & metadata
data.collection <- getDataCollection(params$data.directory)
# data.y.0 <- getData(data.collection,"ZEI010AD1.TXT")[[2]]
data.y.0 <- getData(data.collection,params$data.collection[1])[[2]]
# data.q.0 <- tail(getData(data.collection,"ZEI010AD2.TXT")[[2]],13)
data.q.0 <- tail(getData(data.collection,params$data.collection[2])[[2]],13)
# meta <- getData(data.collection,"ZEI010AD1.TXT")[[1]]
meta <- getData(data.collection,params$data.collection[1])[[1]]

#select series
series <- c(1, #variable
            2, #France
            3, #Germany
            4, #Austria
            5, #Belgium
            6, #Spain
            7, #Finland
            8, #Greece
            9, #Ireland
            10, #Italy
            11, #Luxembourg
            12, #Netherlands
            13, #Portugal
            14, #Slovenia
            15) #Euro area 

if (all(is.na(tail(data.y.0[,tail(series,length(series)-1)],1)))) { #if last obs is NA then shift one previous
  end <- nrow(data.y.0)-1
  begin <- end-3
  data.y <- t(data.y.0[begin:end,series])
  rm(begin,end)
} else
  data.y <- t(tail(data.y.0[,series],3))

data.q <- t(data.q.0[,series])

#set metadata:
met <- as.character(meta[2,series])
met <- trimws(unlist(lapply(strsplit(met,":"),"[[",1)))
met <- countrynameFR2EN(met)
c.fi <- getCountryByCode("fi",params$lang)
met <- sub(c.fi,paste0(c.fi," <sup><i>(c)</i></sup>"),met,ignore.case=T)
rm(c.fi)

#generate datatable:

#header:

col.q <- as.yearqtr(as.character(data.q[1,]),"%Y-%m")
# col.q.y <- as.character(format(col.q,"%Y"))
# col.q.q <- as.character(format(col.q,ifelse(params$lang=="FR","T%q","Q%q")))
# t <- base::table(col.q.y)
sep.style <- "box-shadow:-2px 0 0 black;"

sketch = htmltools::withTags(table(
  thead(
    tr(
      th(colspan=1,rowspan=3),
      th(colspan=3,rowspan=1,ifelse(params$lang=="FR","Moyenne annuelle","Annual average")),
      th(colspan=13,rowspan=1,ifelse(params$lang=="FR","Glissement annuel","4-quarterly change"),
         style=sep.style)
    ),
    tr(
      lapply(as.character(data.y[1,]), th, rowspan=2),
      # lapply(seq_along(t),function(x){th(
      #   names(t)[[x]],colspan=t[x],
      #   style=paste0("font-weight:bold; text-align:left; border:none;",ifelse(x==1,sep.style,""))
      # )})
      getTH(base::table(as.character(format(col.q,"%Y"))),"Y")
    ),
    tr(
      getTH(as.character(format(col.q,ifelse(params$lang=="FR","T%q","Q%q"))),"Q")
    )
    # tr(
    #   lapply(utils::head(col.q.q,1), th,
    #          style=paste0("font-weight:normal; ",sep.style)),
    #   lapply(tail(col.q.q,length(col.q.q)-1), th, style="font-weight:normal; ")
    # )
  )
))
rm(t,sep.style)

#end header

#data
data <- as.data.frame(cbind(data.y,data.q), stringsAsFactors=F)
t1 <- genDataTable(data,met,sketch,c("FR","EA"))

#ouput the table
t1

```

```{r}
htmltools::p()
htmltools::p(class="titlechart title",
             ifelse(params$lang=="FR","Coût salarial horaire","Hourly wage cost"),
             tags$sup("(b)")
             )
```

```{r}

#select series
series <- c(1, #variable
            16, #France
            17, #Germany
            18, #Austria
            19, #Belgium
            20, #Spain
            21, #Finland
            22, #Greece
            23, #Ireland
            24, #Italy
            25, #Luxembourg
            26, #Netherlands
            27, #Portugal
            28, #Slovenia
            29) #Euro area 

data.y <- t(data.y.0[,series])
data.q <- t(data.q.0[,series])

#set metadata:
#same as for t1

#generate datatable:

#header:
#same as for t1

#data:
data <- as.data.frame(cbind(data.y,data.q), stringsAsFactors=F)
t2 <- genDataTable(data,met,sketch,c("FR","EA"))

#ouput the table
t2

```


```{r}

footer <- htmltools::withTags(
  list(
    p(style="text-align: left; font-style: italic; line-height: 50%;",
      ifelse(params$lang=="FR",
             "Basé sur la méthodologie NACE révision 2",
             "Based on methodology NACE revision 2")),
    tags$ol(class="laparent",style="font-style: italic; padding-left: 3px;",
            tags$li(HTML(ifelse(params$lang=="FR",
                                "En plus des salaires bruts des employés, les co&ucirc;ts totaux de la main-d'&oelig;uvre incluent les coûts indirects tels que les cotisations sociales à la charge des employeurs et les imp&ocirc;ts liés à l'emploi",
                                "In addition to employees' gross earnings, total labour costs include indirect costs such as employers' social contributions and taxes connected to the
employment"))),
tags$li(HTML(ifelse(params$lang=="FR",
                    "Ensemble de l'économie excluant l'agriculture, la p&ecirc;che et le secteur public",
                    "Whole economy excluding agriculture, fishing and government sectors"))),
tags$li(HTML(ifelse(params$lang=="FR",
                    "Données brutes","Unadjusted")))
    ),
p(style="text-align: left;",
  "Source Eurostat",
  span(style="float:right;",
       paste0(ifelse(params$lang=="FR",
                     "Réalisé le ",
                     "Produced on "),
              format(Sys.Date(),"%e %B %Y"))))
  )
)

footer <- setFooter(footer)

#output footer:
footer

```


