---
always_allow_html: yes
output:
  html_document: default
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE)
knitr::read_chunk("../../R/data.R")
knitr::read_chunk("../../R/ccze_init.R")
knitr::read_chunk("../../R/ccze_footer.R")
```
```{r}
<<init>>
<<data>>
```
```{r include=T}
includeCSS("../../css/ccze.css")
```
```{r}
data.collection <- getDataCollection("../../data/input/ze!nonquot")
```

## Indicateurs de performances au sein de la zone euro

***
<p style="text-align: right; font-size:90%; font-style: italic;">*Glissement annuel en pourcentage*</p>
<p class="titlechart">**Co&ucirc;t total horaire de la main-d'&oelig;uvre** *(a)(b)*</p>

```{r}

#get data & metadata
data <- getData(data.collection,"ZEI010BD1.TXT")[[2]]
meta <- getData(data.collection,"ZEI010BD1.TXT")[[1]]

#select series
series <- c(1, #variable
            2, #France
            3, #Germany
            5, #Spain
            8, #Euro area
            4, #Belgium
            6, #Italy
            7) #Netherlands 

#set date periods to quarter format
data$date <- format(as.yearqtr(data$date,"%Y-%m"),"T%q %Y")

#keep current year + 7 previous whole years
end.period <- tail(grep("T1",data$date),1)
begin.period <- end.period-28
end.period <- length(data$date)
periods <- rev(seq(end.period,begin.period,-1))
dat <- data[periods,series]

rm(begin.period,end.period,periods)

#set metadata
met <- as.character(meta[2,series])
met <- trimws(unlist(lapply(strsplit(met,":"),"[[",1)))

#min and max of Y-Axis for the two charts
c_max <- ceiling(max(dat[,-c(1)]))
c_min <- floor(min(dat[,-c(1)]))

#chart 1
c1 <- highchart(width=450) %>%
  hc_exporting(enabled=T) %>%
  hc_colors(c(style.color.FR,style.color.DE,style.color.ES,style.color.EA,style.color.BE,style.color.IT,style.color.NL)) %>%
  hc_plotOptions(
    line=list(marker=list(enabled=F))) %>%
  hc_tooltip(valueDecimals=1,shared=T,valueSuffix=" %") %>%
  # hc_legend(width=450,itemDistance=50,layout="vertical",align="right") %>%
  hc_legend(layout="vertical",verticalAlign="middle",align="right") %>%
  hc_xAxis(categories=dat[,1],
           labels=list(formatter=JS("function () {
                var label=(this.value).toString();
                var res=(label.replace(' ','<br>')).replace(/\\d{2}(?=\\d{2})/,'');
                return res;
            }")),
           gridLineWidth=1,tickInterval=4) %>%
  hc_yAxis(min=c_min,max=c_max,startOnTick=F,endOnTick=F,allowDecimals=F,minPadding=0,maxPadding=0,tickInterval=1) %>%
  hc_add_series(name=met[2],data=dat[,2], id=met[2], lineWidth=3) %>%
  hc_add_series(name=met[3],data=dat[,3], id=met[3]) %>%
  hc_add_series(name=met[4],data=dat[,4], id=met[4]) %>%
  hc_add_series(name=met[5],data=dat[,5], id=met[5], lineWidth=3) %>%
  hc_add_series(name=met[6],id=met[6]) %>% #fake series (for sharing legend)
  hc_add_series(name=met[7],id=met[7]) %>%
  hc_add_series(name=met[8],id=met[8])
  
#chart 2
c2 <- c1 %>%
  hc_legend(enabled = FALSE) %>%
  hc_colors(c(style.color.EA,style.color.BE,style.color.IT,style.color.NL)) %>%
  # hc_rm_series(name=c(met[2],met[3],met[4])) %>% #keep Euro area
  hc_rm_series(name=c(met[2],met[3],met[4],met[6],met[7],met[8])) %>% #keep Euro area
  hc_add_series(name=met[6],data=dat[,6], id=met[6]) %>%
  hc_add_series(name=met[7],data=dat[,7], id=met[7]) %>%
  hc_add_series(name=met[8],data=dat[,8], id=met[8])

#share the legend between the charts
c1 <- c1 %>%
  hc_plotOptions(series = list(events = list(legendItemClick = sharelegend)))

#ouput the charts in HTML
div(class = "hc-link-legend",
  c1,
  c2
)
  
```

<!-- <table><tr> -->
<!-- <td width="50%"> -->

<!-- ```{r} -->
<!-- c1 -->
<!-- ``` -->

<!-- </td> -->
<!-- <td width="50%"> -->

<!-- ```{r} -->
<!-- c2 -->
<!-- ``` -->

<!-- </td> -->

<!-- </tr></table> -->

```{r eval = T}
<<footer>>
```


