---
always_allow_html: yes
output:
  html_document:
    css: ../../css/ccze.css
params:
  data.directory: "../../data/input/manual"
  data.collection: !r c("industry_total_sa_nace2.xlsx")
  data.params: !r c("INDUSTRY MONTHLY")
  data.template: !r c("bdf.manual.xlsx")
  lang: "FR"
  numpage: 13
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = FALSE)
knitr::read_chunk("../../R/tool.R")
knitr::read_chunk("../../R/data.R")
knitr::read_chunk("../../R/ccze_init_table.R")
```
```{r}
<<init>>
<<tool>>
<<data>>
```

```{r}
htmltools::h3(class="pub",ifelse(params$lang=="FR","Activité : indicateur de confiance dans l'industrie","Activity: industrial confidence indicator"))
htmltools::hr(class="pub")
htmltools::p(class="unitlegend",ifelse(params$lang=="FR","solde des opinions","balance of opinions"))
```

```{r}

#get data & metadata
data.collection <- getDataCollection()
data.0 <- getData(data.collection,"industry_total_sa_nace2.xlsx")
meta <- data.0[[1]] #metadata
data.0 <- data.0[[2]] #data

#select series
series <- c(1, #variable
            2, #France
            3, #Germany
            4, #Austria
            5, #Belgium
            6, #Cyprus
            7, #Spain
            8, #Estonia
            9, #Finland
            10, #Greece
            11, #Ireland
            12, #Italy
            13, #Latvia
            14, #Lithuania
            15, #Luxembourg,
            16, #Malta
            17, #Netherlands
            18, #Portugal
            19, #Slovakia
            20, #Slovenia
            21, #Euro area
            22, #Bulgaria
            23, #Croatia
            24, #Denmark
            25, #Hungary
            26, #Poland
            27, #Romania
            28, #United Kingdom
            29, #Sweden
            30, #Czech Republic
            31) #European union

data <- t(data.0[,series])

#set metadata:
met <- as.character(meta[2,series])
# met <- trimws(unlist(lapply(strsplit(met,":"),"[[",1)))
# met <- countrynameFR2EN(met)
met <- getCountryByCode(met)

#generate datatable:

#header:

# col.m.mc <- zoo::as.yearmon(as.character(data.m.mc[1,]),"%Y-%m")
# col.m.yoy <- zoo::as.yearmon(as.character(data.m.yoy[1,]),"%Y-%m")
col <- zoo::as.yearmon(as.character(data),"%Y-%m")
style.sep <- ""

getTH <- function(variable,liblevel) {
  
  style.fwn <- "font-weight:normal; "
  style.fwb <- "font-weight:bold; text-align:left; border:none;"
  
  res <- htmltools::withTags(
    if (liblevel=="Y") {
      lapply(
        seq_along(variable),
        function(x){th(
          names(variable)[[x]],colspan=variable[x],
          style=paste0(style.fwb,ifelse(x==1,style.sep,""))
        )}) 
    } else { # "M"
      list(
        lapply(utils::head(variable,1),th,style=paste0(style.fwn,style.sep)),
        lapply(tail(variable,length(variable)-1), th, style=style.fwn)
      )
    }
  )
  
  return(res)
  
}

sketch = htmltools::withTags(table(
  thead(
    tr(
      th(colspan=1,rowspan=2),
      getTH(base::table(as.character(format(col,"%Y"))),"Y")
    ),
    tr(
      lapply(as.character(data.y[1,]), th, rowspan=2),
      getTH(base::table(as.character(format(col.m.mc,"%Y"))),"Y"),
      getTH(base::table(as.character(format(col.m.yoy,"%Y"))),"Y")
    ),
    tr(
      getTH(as.character(format(col.m.mc,"%b")),"M"),
      getTH(as.character(format(col.m.yoy,"%b")),"M")
    )
  )
))

rm(list=ls(pattern="style\\.(sep|fwn|fwb)|t\\.|col\\.")) #clean-up

#end header

#data
data <- as.data.frame(cbind(data.y,data.m.mc,data.m.yoy), stringsAsFactors=F)
t1 <- genDataTable(data,met,sketch,c("France","Zone euro","Union européenne"))

#ouput the table
t1

```

<p>&nbsp;</p>

```{r}

#generate footer:

footer <- htmltools::withTags(
  list(
    # p(style="text-align: left; font-style: italic; line-height: 50%;",
    #   ifelse(params$lang=="FR",
    #          "Indices nationaux sauf pour la Zone euro et l'Union européenne",
    #          "Harmonised indices except for the euro area and European Union")),
    p(style="text-align: left;",
      ifelse(params$lang=="FR",
             "Sources : Commission européenne",
             "Sources: European Commission"),
      span(style="float:right;",
           paste0(ifelse(params$lang=="FR",
                         "Réalisé le ",
                         "Produced on "),
                  format(Sys.Date(),"%e %B %Y"))))
  )
)

footer <- setFooter(footer)

#output footer:
footer

```


